name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu    
    steps:
      - uses: actions/checkout@v4
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: '.'
          destination-github-username: 'JuanjisGP'
          destination-repository-name: 'pushFromAnotherRepo'
          user-email: jjc.gp12@gmail.com
          commit-message: "probando a actualizar desde otro repo"
          target-branch: develop
