name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex    # "ubuntu" is a more generic container check this later
                               # using "pandoc/latex" because of dependencies
                               # used in the specific "build.sh"
    steps:
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: '.'
          destination-github-username: 'JuanjisGP'
          destination-repository-name: 'pushFromAnotherRepo'
          user-email: jjc.gp12@gmail.com
          target-branch: main
